import {useState} from 'react'; import {Bell,Home,LibraryBig,Users,Inbox,Settings,Plus,Play,Search,MoreHorizontal,ChevronRight,Archive,UserPlus,Check,X,ArrowLeft,Send,Volume2,Maximize2} from 'lucide-react'; import './styles.css';
const sessions=[['Гравити Фолз — 2 сезон','VK Видео','https://images.unsplash.com/photo-1519608487953-e999c86e7455?auto=format&fit=crop&w=900&q=80','62%','4'],['Шрек 2','Google Drive','https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&w=900&q=80','31%','2'],['Старый сериал — серия 4','VK Видео','https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=900&q=80','8%','3']];
const friends=[['Kira','https://i.pravatar.cc/160?img=32',true],['Alex','https://i.pravatar.cc/160?img=14',true],['Mizu','https://i.pravatar.cc/160?img=47',false],['Nik','https://i.pravatar.cc/160?img=51',false]];
function Nav({page,setPage}:{page:string,setPage:(p:string)=>void}){let a=[['home','Главная',Home],['sessions','Сессии',LibraryBig],['friends','Друзья',Users],['invites','Приглашения',Inbox],['settings','Настройки',Settings]] as const; return <nav>{a.map(([id,t,I])=><button className={page===id?'active':''} onClick={()=>setPage(id)} key={id}><I size={19}/><span>{t}</span></button>)}</nav>}
function Card({s,open}:{s:string[],open:()=>void}){return <button className="card" onClick={open}><div className="thumb"><img src={s[2]} /><span className="source">{s[1]}</span><span className="play"><Play size={17} fill="currentColor"/></span></div><div className="ci"><div><b>{s[0]}</b><small>сегодня · {s[3]}</small></div><span><Users size={14}/> {s[4]} <MoreHorizontal size={18}/></span></div><div className="progress"><i style={{width:s[3]}}/></div></button>}
function Home({open,setPage}:{open:()=>void,setPage:(p:string)=>void}){return <Page><header><div className="brand"><i><Play size={12} fill="currentColor"/></i>Wathis</div><div className="actions"><button><Search size={19}/></button><button onClick={()=>setPage('invites')} className="bell"><Bell size={19}/><em>2</em></button><img src="https://i.pravatar.cc/160?img=12"/></div></header><section className="hero"><div><label>✦ WATHIS</label><h1>Смотри то,<br/><strong>что хочется.</strong></h1><p>Создай комнату, позови друзей и продолжи просмотр там, где остановился.</p><button className="primary" onClick={open}><Plus size={17}/>Создать сессию</button></div><div className="mascot"><div>W</div><span>Вачис</span></div></section><Title t="Продолжить" a="Все" click={()=>setPage('sessions')}/><div className="cards">{sessions.slice(0,2).map((s,i)=><Card s={s} open={open} key={i}/>)}</div><Title t="Сейчас смотрят"/><button className="live" onClick={open}><div className="stack">{friends.slice(0,3).map(f=><img src={f[1] as string} key={f[0]}/>)}</div><div><b>Ночная кинопати</b><small><i/>4 человека смотрят сейчас</small></div><span>›</span></button></Page>}
function Title({t,a,click}:{t:string,a?:string,click?:()=>void}){return <div className="title"><h2>{t}</h2>{a&&<button onClick={click}>{a}</button>}</div>}
function Page({children}:{children:React.ReactNode}){return <main>{children}</main>}
function Sessions({open}:{open:()=>void}){return <Page><header className="simple"><div><label>БИБЛИОТЕКА</label><h1>Мои сессии</h1></div><button className="round"><Plus size={20}/></button></header><div className="limit"><Archive size={18}/><div><b>3 из 10</b><small>сессий сохранено</small></div><span><i/></span></div><Title t="Сохранённые"/><div className="cards">{sessions.map((s,i)=><Card s={s} open={open} key={i}/>)}</div></Page>}
function Friends(){return <Page><header className="simple"><div><label>СОЦИАЛЬНОЕ</label><h1>Друзья</h1></div><button className="round"><UserPlus size={20}/></button></header><div className="search"><Search size={17}/><input placeholder="Найти друга..."/></div><Title t="4 друга"/><div className="users">{friends.map(f=><div className="user" key={f[0]}><div className="av"><img src={f[1] as string}/>{f[2]&&<i/>}</div><div><b>{f[0]}</b><small>{f[2]?'В сети':'Не в сети'}</small></div><MoreHorizontal size={19}/></div>)}</div></Page>}
function Invites(){return <Page><header className="simple"><div><label>ВХОДЯЩИЕ</label><h1>Приглашения</h1></div></header><Title t="Новые"/><div className="invite"><img src={friends[0][1] as string}/><div><b>Kira приглашает вас</b><small>«Ночная кинопати» · 4 участника</small><em>только что</em></div><button><Check size={17}/></button><button><X size={17}/></button></div><div className="empty"><strong>✦</strong><b>Здесь будут ваши приглашения</b><small>Они не потеряются в чате.</small></div></Page>}
function Settings(){let r=[['Внешний вид','Тема и оформление'],['Уведомления','Приглашения и события'],['Приватность','Кто может приглашать вас'],['Воспроизведение','Качество и поведение плеера']];return <Page><header className="settingsHead"><div className="brand"><i><Play size={12} fill="currentColor"/></i>Wathis</div><span>Настройки</span></header><div className="profile"><div>W</div><section><b>Кабуничек</b><small>@wathis_user</small></section><button>Изменить</button></div><div className="settings">{r.map(([a,b])=><button key={a}><span>✦</span><section><b>{a}</b><small>{b}</small></section><ChevronRight size={18}/></button>)}</div><p className="version">Wathis · prototype 0.1</p></Page>}
function Room({back}:{back:()=>void}){let [play,setPlay]=useState(true),[msg,setMsg]=useState('');return <div className="room"><header className="roomHead"><button onClick={back}><ArrowLeft size={21}/></button><div><b>Ночная кинопати</b><small><i/>4 участника</small></div><button><MoreHorizontal size={21}/></button></header><div className="player"><img src="https://images.unsplash.com/photo-1519608487953-e999c86e7455?auto=format&fit=crop&w=1400&q=85"/><span className="now">Wathis · VK Видео</span><button className="bigplay" onClick={()=>setPlay(!play)}>{play?<span>Ⅱ</span>:<Play size={26} fill="currentColor"/>}</button></div><div className="pc"><div className="timeline"><i/></div><div><span>1:24:32</span><section><button><Volume2 size={18}/></button><button><Maximize2 size={17}/></button></section><span>2:13:40</span></div></div><section className="roomBody"><label>СЕЙЧАС СМОТРИТЕ</label><h1>Гравити Фолз — 2 сезон</h1><div className="roomButtons"><button>♟ 4 участника</button><button>＋ Пригласить</button></div><div className="chat"><div className="chatTitle"><b>Чат</b><span>сейчас</span></div><Bubble name="Kira" text="Ну всё, погнали 😭"/><Bubble name="Alex" text="Я уже включил"/><Bubble name="Кабуничек" text="ахахаха смотрите на него" mine/><small className="system">♛ Кабуничек — администратор</small></div></section><form onSubmit={e=>{e.preventDefault();setMsg('')}}><input value={msg} onChange={e=>setMsg(e.target.value)} placeholder="Написать сообщение..."/><button><Send size={17}/></button></form></div>}
function Bubble({name,text,mine=false}:{name:string,text:string,mine?:boolean}){return <div className={'bubble '+(mine?'mine':'')}><small>{name}</small><span>{text}</span></div>}
export default function App(){let [page,setPage]=useState('home');let [room,setRoom]=useState(false);if(room)return <Room back={()=>setRoom(false)}/>;return <div className="app"><div className="glow g1"/><div className="glow g2"/>{page==='home'?<Home open={()=>setRoom(true)} setPage={setPage}/>:page==='sessions'?<Sessions open={()=>setRoom(true)}/>:page==='friends'?<Friends/>:page==='invites'?<Invites/>:<Settings/>}<Nav page={page} setPage={setPage}/></div>}